### ISSUE TITLE
_id is not generated if omitted in insert and bulkInsert API

### ISSUE THREAD

**Issue by evgolsh** [wix/velo-external-db#192]
This code was working previously and now fails if _id is not explicitly set.

`import wixData from 'wix-data';

export async function insertTest(event) {

	// const item = {column_0: 'insert test1', column_1: 'test 1', _id: 'kkk1'} ; // works
	const item = {column_0: 'insert test1', column_1: 'test 1'} ; // fails with unknown error

	const res = await wixData.insert('velo-demo/demo1', item);
`

**Comment by a1gucis** [comment]
Ids should be assigned at the connector layer.

**Comment by Idokah** [comment]
Maybe it worked in the first time because the _id was : '' and then in the second time it doesn't allow duplication for the _id column.

**Comment by Idokah** [comment]
We can generate _id if it's not provided by the user, as the content manger does. 
@noam-almog WDYT?

**Comment by noam-almog** [comment]
we already generate _id, we do it on the prepare stage: https://github.com/wix/velo-external-db/blob/master/packages/velo-external-db-core/lib/converters/item_transformer.js#L40
as far as i know, we don't throw validation errors on insert, please investigate
