### ISSUE TITLE
Postgres connector is broken for inserts

### ISSUE THREAD

**Issue by evgolsh** [wix/velo-external-db#195]
When trying to insert data to a Postgres database from Content manager it constantly fails with the following error:

`Error: Unrecognized operator 0 at FilterTransformer.wixOperatorToAdapterOperator (/usr/lib/app/packages/velo-external-db-core/lib/converters/filter_transformer.js:72:23) at FilterTransformer.transform (/usr/lib/app/packages/velo-external-db-core/lib/converters/filter_transformer.js:26:31) at /usr/lib/app/packages/velo-external-db/lib/router.js:140:95 at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by MXPOL** [comment]
@evgolsh 
Have this happened once? 
Have you set any filters?

**Comment by evgolsh** [comment]
I'm using the pre-built image. It is constantly reproducible if you try either insert or update any data

**Comment by evgolsh** [comment]
Still getting
`Error: Unrecognized operator 0
    at FilterTransformer.wixOperatorToAdapterOperator (/usr/lib/app/packages/velo-external-db-core/lib/converters/filter_transformer.js:72:23)
    at FilterTransformer.transform (/usr/lib/app/packages/velo-external-db-core/lib/converters/filter_transformer.js:26:31)
    at /usr/lib/app/packages/velo-external-db/lib/router.js:140:95
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

and 

> "Validation error. No message from connector."

on /data/count calls
