### ISSUE TITLE
The behavior of the startsWith operator does not match the operator description

### ISSUE THREAD

**Issue by MXPOL** [wix/velo-external-db#209]
The behavior of the `startsWith` operator does not match the [operator description](https://www.wix.com/velo/reference/wix-data/wixdatafilter/startswith) in all database engines.

The operator should not be case-sensitive, contrary to what is happening now

**Comment by evgolsh** [comment]
We have two option to fix that:

1. Normalize a field before querying a DB, e.g. LOWER(column) like startsWith%. The biggest downside of this approach is that it would hardly hurt index performance.
2. Use DB engine specific solutions, like changing LIKE to ILIKE for Postgres etc.
