### ISSUE TITLE
What is the supported version of MongoDB

### ISSUE THREAD

**Issue by johnlsg** [wix/velo-external-db#282]
I tried mongodb version 5.0.7 community with this adaptor. But the adaptor keeps returning "Collection does not exists". I suspect it is developed for older version of MongoDB

**Comment by MXPOL** [comment]
Hey @johnlsg, 

The problem isn't related to the MongoDB version, but with the way MongoDB works. 
In contrast to relational databases, MongoDB is a schema-free, meaning that you can add any field to any document in your collection.
To overcome this problem, it's necessary to add a new collection called `_descriptor`, this collection will describe what collections you want to use via the adapter and which fields there are in each collection and what their types.
Any document in the `_descriptor`should include `_id` field and the value of this field is the name of the collection, in addition, this document should include the `fields` field Its value should be an array of objects that describe the column name and the data type .

For example suppose I have a collection called `customers`, and each document in this collection has the following fields: cName, dateOfBirth. so the document that describes this collection in the `_descriptor` collection will look like this:
`{ _id: 'customers', fields: [{ name: 'cName', type: 'text'}, { name: 'dateOfBirth', type: 'datetime' }] }`

The filed types can `number` ,`text`, `datetime` `boolean` and `object`

After you go through this process, you're supposed to see the collection via the adapter.

**Comment by johnlsg** [comment]
I see, I thought the _descriptor collection is a system collection of MongoDB, thanks for clarifying.
