### ISSUE TITLE
Unsupported column type handling

### ISSUE THREAD

**Issue by Idokah** [wix/velo-external-db#350]
Add support for bit type in mssql.
Throw appropriate error on unknown type (or use other behaviour)

**Comment by MXPOL** [comment]
We need to think about the behavior of the adapter when it encounters a data type it doesn’t support.
I have already helped to two clients whose their adapter stopped working, because they added a table with unsupported columns

**Comment by Idokah** [comment]
@MXPOL  WDYT about returning any unknown type as text ? 
It's not perfect, but it's better than the current situation... 

@michaelir
