### ISSUE TITLE
Azure - Wix Connection

### ISSUE THREAD

**Issue by nvmundial** [wix/velo-external-db#412]
Hi! Thank you in advance for your valuable help. I'm receiving the following error after doing all the steps to connect Wix to Azure. o anyone understand what would be happening or how to fix it?

Thank you

<img width="882" alt="Screenshot 2023-02-07 at 12 20 04 PM" src="https://user-images.githubusercontent.com/124719412/217338135-623e039c-6d0d-47f4-aa27-1672989f8dbe.png">

**Comment by Idokah** [comment]
Hi @nvmundial in you're mysql instance, connection security, try to mark disable in SSL enforcment
![image](https://user-images.githubusercontent.com/82806105/217564923-05e21f73-12b2-4117-97aa-da05f4464b25.png)

**Comment by nvmundial** [comment]
Thank you so much! It worked yesterday. However now I'm having a new, different error. 

<img width="683" alt="Screenshot 2023-02-08 at 3 34 27 PM" src="https://user-images.githubusercontent.com/124719412/217645236-58e62b77-bba7-41bf-98f0-14a05f4b3ef4.png">

**Comment by Idokah** [comment]
Can you send here the app logs?

**Comment by nvmundial** [comment]
Thank you so so much!! Please let me know if you need something else. 

<img width="1240" alt="Screenshot 2023-02-09 at 10 49 02 AM" src="https://user-images.githubusercontent.com/124719412/217864152-77ad53e7-c565-433a-82f0-48ad4c0e79fe.png">

**Comment by nvmundial** [comment]
Not sure if the "Extracting" log is normal. But it appears a lot. 

Thank you for your help, you are my hero.

**Comment by Idokah** [comment]
Please try to redeploy with this docker image name : 
`veloex/velo-external-db:latest`

**Comment by jndjndjnd** [comment]
I am having the same issue (cannot be mapped to a host ID). How was this resolved?

**Comment by nvmundial** [comment]
Hi! I redeployed with veloex/velo-external-db:mysql and worked. Let me know
if it works for you.

**Comment by jndjndjnd** [comment]
Thank you! I got the Wix page, but Authorization Config Status is yellow, and Connection Status is red.
![image](https://user-images.githubusercontent.com/125571423/219401868-4ac7c6a3-aa00-4ead-bc7d-81ea4a6702bb.png)

**Comment by Idokah** [comment]
About the yellow authorization it's fine, it means it just using the default.
About the connection status is red-check that the host name in the environment variable is correct.

**Comment by jndjndjnd** [comment]
The host name in the secret is correct, but I still get the same error.

**Comment by nvmundial** [comment]
Check if it's a MySQL server.

**Comment by dudecuda** [comment]
So I figured out why the deployment error, though haven't gotten a response from wix yet.
Because the most recent ("latest") update on docker was 21 days ago, and essentially broke things if following stricly from the tutorial listed here:

https://support.wix.com/en/article/velo-integrate-your-azure-database-with-your-wix-site

The package has a unique ID called a UID. The part that it's not liking is that linux can only read UIDs so high by default, and the most recent update is above linux's maximum allowed. 

Someone on wix's end needs to change the package with UID 718322462 (mine shows the same error when on "latest") to one that Linux will support. Fixing this in the update will fix the bug (though github's seems to be the old one).

Until then, anyone affected can use the veloex/velo-external-db:mysql one instead, but in my case as well, this seems to not work with the permissions JSON (I have modified many different ways, it really doesn't seem to like any iteration)

My hope is that someone will see this, take the few minutes to tweak the UID and go back to the latest build. In the wait, would be nice if anyone had any ideas on how to fix the permissions component on the mysql deployment

**Comment by Idokah** [comment]
> So I figured out why the deployment error, though haven't gotten a response from wix yet. Because the most recent ("latest") update on docker was 21 days ago, and essentially broke things if following stricly from the tutorial listed here:
> 
> https://support.wix.com/en/article/velo-integrate-your-azure-database-with-your-wix-site
> 
> The package has a unique ID called a UID. The part that it's not liking is that linux can only read UIDs so high by default, and the most recent update is above linux's maximum allowed.
> 
> Someone on wix's end needs to change the package with UID 718322462 (mine shows the same error when on "latest") to one that Linux will support. Fixing this in the update will fix the bug (though github's seems to be the old one).
> 
> Until then, anyone affected can use the veloex/velo-external-db:mysql one instead, but in my case as well, this seems to not work with the permissions JSON (I have modified many different ways, it really doesn't seem to like any iteration)
> 
> My hope is that someone will see this, take the few minutes to tweak the UID and go back to the latest build. In the wait, would be nice if anyone had any ideas on how to fix the permissions component on the mysql deployment

Hi, about this, you're right, we fixed it, and you can now use the latest tag again.

**Comment by dudecuda** [comment]
> > So I figured out why the deployment error, though haven't gotten a response from wix yet. Because the most recent ("latest") update on docker was 21 days ago, and essentially broke things if following stricly from the tutorial listed here:
> > https://support.wix.com/en/article/velo-integrate-your-azure-database-with-your-wix-site
> > The package has a unique ID called a UID. The part that it's not liking is that linux can only read UIDs so high by default, and the most recent update is above linux's maximum allowed.
> > Someone on wix's end needs to change the package with UID 718322462 (mine shows the same error when on "latest") to one that Linux will support. Fixing this in the update will fix the bug (though github's seems to be the old one).
> 
> Hi, about this, you're right, we fixed it, and you can now use the latest tag again.
> 
> > Until then, anyone affected can use the veloex/velo-external-db:mysql one instead, but in my case as well, this seems to not work with the permissions JSON (I have modified many different ways, it really doesn't seem to like any iteration)
> > My hope is that someone will see this, take the few minutes to tweak the UID and go back to the latest build. In the wait, would be nice if anyone had any ideas on how to fix the permissions component on the mysql deployment
> 
> About the permissions, can you elaborate?

So I think I just discovered something in the mysql distro that doesn't behave like the full latest. See attached, nothing I did would yield any other message than the one shown. As soon as I switched to the fixed latest, everything automagically worked again with the same settings. It does seem like something with the mysql distro handles this differently and won't register any permissions entered. 

The fix resolved my issue and permissions now works fine on the latest build, but wouldn't hurt to have the other if there ever was a reason to downgrade again.

![permissions config](https://user-images.githubusercontent.com/94335388/222235921-417a97c8-9ae0-4ec3-9e82-3ab74fb20ab7.png)

**Comment by Idokah** [comment]
Hi, the current mysql image is deprecated, stick to the latest meanwhile.

**Comment by nvmundial** [comment]
It's great that it looks like it works now. But it really worries me that they took 3 weeks to fix it. If something like that happens again my business is over. Idokah, Can we have a working backup somehow?

**Comment by dudecuda** [comment]
Yeah, kinda echoing what nvmundial said. This came up while pitching the purchase of a wix website. It was really a nail-biter moment. It was nice to have the mysql backup to keep working and show a previews, but not a great assurance in my data not being visible to site visitors. 

It was very helpful to have anything proven functional with my site to rely on, that perhaps it might be wise to have the last functional release available when pushing to a new one. It would have solved the issue many days earlier, and many might not be as sleuth at digging through the logs as I was. Switching to an old release is such an easy fix in pinch moments (could also be added as an easy addition in the guide, as it's own main go to when trying to fix issues)

**Comment by Idokah** [comment]
I pushed to the tag `:mysql` the same image for backup.
Sorry for the late fix.

**Comment by nvmundial** [comment]
But :mysql don't support Permissions, correct? Can we have 2?

**Comment by nvmundial** [comment]
Good to know! Thank you.
