### ISSUE TITLE
Insert data doesn't work with MySQL

### ISSUE THREAD

**Issue by evgolsh** [wix/velo-external-db#81]
I'm connecting the adapter to MySQL database, using all the system fields for read-write support in a table. When I open the table in the Content Manager, I'm able to insert only one first row. All the next attempts to add rows fail with "Server isn't responding, Retrying..." message. It works properly when working with Postgres database.

**Comment by Idokah** [comment]
@evgolsh 
It's because we are returning `{ protocolVersion:2 }` in the `/provision` before we adjusted our adapter to work with this protocol.

**Comment by evgolsh** [comment]
Fixed in the latest release
