### ISSUE TITLE
Wrap API 

### ISSUE THREAD

**Issue by Idokah** [wix/velo-external-db#98]
I want to make a class `ApiWrapper` to wrap the data API from Wix and transform it to our Adapter API for 2 main reasons:

-  Make adjusting to a new API easier in the future
-  Make the `sql_filter_transformer.js` files more readable (instead of parsing every filter in the begging of the function to `operator, fieldName, value` send the filter already parsed to the function)

It will be a bit similar to V1Filter - not because it's easier, I Just think that this format is very  reasonable, but you can offer another format:

Wix's operators to adapter operators: 

```
- $contains := string_contains
- $startsWith := string_begins
- $endsWith := string_ends
- $eq :=  eq
- $ne := ne
- $lt := lt
- $lte := lte
- $gt := gt
- $gte := gte
- $hasSome := in
- $or := or
- $and := and
- $not := not
```

Wix filter today: 
```
filter:
{
  'theFieldName':  { WixOperator:  'val' }
}
```

will change to: 
```
filter:
{
  fieldName: 'theFieldName'
  operator: adapterOperator
  value: 'val'
}
```
Or in case of  **or**  /  **and** / **not** operators 
from :
```
filter:
{
  WixOperator: [ WixFilter, WixFilter...]
}
```
to:
```
filter:
{
  operator: adapterOperator
  value: [AdapterFilter, AdapterFilter...]
}
```

Wix Functions to adapter functions:

```
- $avg := avg
- $max := max
- $min := min
- $sum := sum
- {$sum:1} := count
```

example for aggregation:
```
const filter = wixData.filter().eq("field3", 'filterValue');
const having = wixData.filter().eq("field2", 'havingValue');

wixData.aggregate("localSpanner/riwpi")
  .filter(filter)
  .group('groupByFieldName', 'groupByFieldName2')
  .max("field1")
  .having(having)
```

today:
```
{  
  filter: { field3: { '$eq': 'filterValue' } },
  processingStep: {
    _id: { field1: '$groupByFieldName', field2: '$groupByFieldName2' },
    field1Max: { '$max': '$field1' }
  }
  postFilteringStep: { field2: { '$eq': 'havingValue' } }
} 
```

will change to: 

```
{
  filter: { adapterFilter }, 
  projection: [{fieldName:'groupByFieldName', fieldAlias: 'groupByFieldName'}, 
                {fieldName:'groupByFieldName2', fieldAlias:'groupByFieldName2'}, 
                {fieldName: 'field1', fieldAlias:'field1Max', functionName: 'max'} ]
  postFilter: { adapterFilter }
}
```

**Comment by noam-almog** [comment]
i think we can pack functions to projection object
so you can define constant fields, or fields with function on them, WDYT ?

**Comment by noam-almog** [comment]
also naming is too coupled with mysql, having for example is a postFilter
group by should probably be aggregate
i think we can talk about the main structure, post filter does not exist if aggregation is not set, perhaps we should pack them into the same object ? (i think we changed it once already so lets discuss)

**Comment by Idokah** [comment]
@noam-almog changed the aggregation object, WDYT?
